plugins { id 'com.android.application' }

configurations.configureEach {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

android {
    signingConfigs {
        release {
            storeFile file('../signing/project-superhuman-v97.keystore')
            storePassword 'PSH970-LocalFirst-2026-KeepSafe'
            keyAlias 'project-superhuman'
            keyPassword 'PSH970-LocalFirst-2026-KeepSafe'
        }
    }
    namespace 'com.projectsuperhuman.m1x'
    compileSdk 35

    defaultConfig {
        applicationId 'com.projectsuperhuman.m1x'
        minSdk 23
        targetSdk 35
        versionCode 10028
        versionName '9.9.8'
    }
    buildTypes { release { signingConfig signingConfigs.release; minifyEnabled false } }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.4'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'com.google.mlkit:barcode-scanning:17.3.0'
    implementation 'androidx.core:core:1.15.0'
}
