package com.projectsuperhuman.next

internal data class ClinicalMarkerDef(
    val id: String,
    val name: String,
    val unit: String = "",
    val aliases: List<String>,
    val panel: String = "Unclassified",
    val defaultLow: String = "",
    val defaultHigh: String = "",
    val maleLow: String = "",
    val maleHigh: String = "",
    val femaleLow: String = "",
    val femaleHigh: String = ""
)

internal val CLINICAL_MARKER_REGISTRY: List<ClinicalMarkerDef> = listOf(
    ClinicalMarkerDef("wbc", "White blood cells", "10^9/L", listOf("total white cell count", "white blood cell count", "white blood cells", "total white blood", "wbc"), "Full Blood Count", "3.6", "11.0", "", "", "", ""),
    ClinicalMarkerDef("rbc", "Red blood cells", "10^12/L", listOf("red blood cell (rbc) count", "red blood cell count", "red blood cells", "rbc count", "rbc"), "Full Blood Count", "", "", "4.50", "6.50", "3.80", "5.80"),
    ClinicalMarkerDef("haemoglobin", "Haemoglobin", "g/L", listOf("haemoglobin estimation", "hemoglobin estimation", "haemoglobin", "hemoglobin", "hb"), "Full Blood Count", "", "", "130", "180", "115", "165"),
    ClinicalMarkerDef("haematocrit", "Haematocrit", "L/L", listOf("haematocrit", "hematocrit", "packed cell volume", "hct"), "Full Blood Count", "", "", "0.40", "0.54", "0.37", "0.47"),
    ClinicalMarkerDef("mcv", "MCV", "fL", listOf("mean corpuscular volume", "mean cell volume", "mcv"), "Full Blood Count", "80", "100", "", "", "", ""),
    ClinicalMarkerDef("mch", "MCH", "pg", listOf("mean corpusc. haemoglobin(mch)", "mean corpuscular haemoglobin", "mean corpuscular hemoglobin", "mean cell haemoglobin", "mean cell hemoglobin", "mch"), "Full Blood Count", "27", "32", "", "", "", ""),
    ClinicalMarkerDef("mchc", "MCHC", "g/L", listOf("mean corpusc. hb. conc. (mchc)", "mean corpuscular haemoglobin concentration", "mean corpuscular hemoglobin concentration", "mchc"), "Full Blood Count", "310", "350", "", "", "", ""),
    ClinicalMarkerDef("rdw", "RDW", "%", listOf("red blood cell distribut width", "red blood cell distribution width", "red cell distribution width", "rdw"), "Full Blood Count", "10.5", "16.0", "", "", "", ""),
    ClinicalMarkerDef("platelets", "Platelets", "10^9/L", listOf("platelet count", "platelets", "plt"), "Full Blood Count", "140", "400", "", "", "", ""),
    ClinicalMarkerDef("mpv", "MPV", "fL", listOf("mean platelet volume", "mpv"), "Full Blood Count", "8.9", "13.0", "", "", "", ""),
    ClinicalMarkerDef("pdw", "Platelet distribution width", "fL", listOf("platelet distribution width", "pdw"), "Full Blood Count", "8.3", "18.0", "", "", "", ""),
    ClinicalMarkerDef("neutrophils", "Neutrophils", "10^9/L", listOf("neutrophil count", "neutrophils", "neut"), "Full Blood Count", "1.8", "7.5", "", "", "", ""),
    ClinicalMarkerDef("lymphocytes", "Lymphocytes", "10^9/L", listOf("lymphocyte count", "lymphocytes", "lymph"), "Full Blood Count", "1.0", "4.0", "", "", "", ""),
    ClinicalMarkerDef("monocytes", "Monocytes", "10^9/L", listOf("monocyte count", "monocytes", "mono"), "Full Blood Count", "0.2", "0.8", "", "", "", ""),
    ClinicalMarkerDef("eosinophils", "Eosinophils", "10^9/L", listOf("eosinophil count", "eosinophils", "eosin"), "Full Blood Count", "0.1", "0.4", "", "", "", ""),
    ClinicalMarkerDef("basophils", "Basophils", "10^9/L", listOf("basophil count", "basophils", "baso"), "Full Blood Count", "0.02", "0.10", "", "", "", ""),
    ClinicalMarkerDef("nrbc", "Nucleated red blood cells", "10^9/L", listOf("Nucleated red blood cells", "nucleated red blood cell count", "nucleated red blood cell", "nucleated rbc", "nrbc"), "Full Blood Count", "0.00", "0.01", "", "", "", ""),
    ClinicalMarkerDef("ferritin", "Ferritin", "ug/L", listOf("serum ferritin", "ferritin"), "Iron Studies", "", "", "24", "340", "11", "310"),
    ClinicalMarkerDef("iron", "Serum iron", "umol/L", listOf("serum iron level", "serum iron"), "Iron Studies", "11.6", "31.3", "", "", "", ""),
    ClinicalMarkerDef("transferrin", "Transferrin", "g/L", listOf("transferrin level", "serum transferrin", "transferrin"), "Iron Studies", "1.74", "3.64", "", "", "", ""),
    ClinicalMarkerDef("tibc", "TIBC", "umol/L", listOf("total iron binding capacity", "tibc"), "Iron Studies", "", "", "", "", "", ""),
    ClinicalMarkerDef("transferrin_sat", "Transferrin saturation", "%", listOf("transferrin saturation index", "transferrin saturation", "transferrin sat"), "Iron Studies", "20", "45", "", "", "", ""),
    ClinicalMarkerDef("bilirubin", "Total bilirubin", "umol/L", listOf("serum total bilirubin level", "serum total bilirubin", "total bilirubin", "bilirubin"), "Liver Panel", "", "", "", "", "", ""),
    ClinicalMarkerDef("conj_bilirubin", "Conjugated bilirubin", "umol/L", listOf("serum conj bilirubin level", "serum conjugated bilirubin level", "conjugated bilirubin", "conj bilirubin"), "Liver Panel", "0", "7", "", "", "", ""),
    ClinicalMarkerDef("total_protein", "Total protein", "g/L", listOf("serum total protein", "total protein"), "Liver Panel", "60", "80", "", "", "", ""),
    ClinicalMarkerDef("globulin", "Globulin", "g/L", listOf("serum globulin", "globulin"), "Liver Panel", "22", "38", "", "", "", ""),
    ClinicalMarkerDef("albumin", "Albumin", "g/L", listOf("serum albumin", "albumin"), "Liver Panel", "31", "45", "", "", "", ""),
    ClinicalMarkerDef("alt", "ALT", "U/L", listOf("serum alt level", "alanine aminotransferase", "alanine transaminase", "alt"), "Liver Panel", "0", "45", "", "", "", ""),
    ClinicalMarkerDef("alp", "Alkaline phosphatase", "U/L", listOf("serum alkaline phosphatase", "alkaline phosphatase", "alp"), "Liver Panel", "30", "130", "", "", "", ""),
    ClinicalMarkerDef("ast", "AST", "U/L", listOf("ast serum level", "serum ast level", "aspartate aminotransferase", "aspartate transaminase", "ast"), "Liver Panel", "5", "34", "", "", "", ""),
    ClinicalMarkerDef("calcium", "Serum calcium", "mmol/L", listOf("serum calcium"), "Bone Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("adjusted_calcium", "Adjusted calcium", "mmol/L", listOf("serum adjusted calcium conc", "serum adjusted calcium concentration", "adjusted calcium conc", "adjusted calcium"), "Bone Profile", "2.08", "2.48", "", "", "", ""),
    ClinicalMarkerDef("phosphate", "Inorganic phosphate", "mmol/L", listOf("serum inorganic phosphate", "inorganic phosphate", "phosphate"), "Bone Profile", "0.80", "1.50", "", "", "", ""),
    ClinicalMarkerDef("tsh", "Serum TSH", "mIU/L", listOf("Serum TSH", "serum tsh level", "thyroid stimulating hormone", "thyroid-stimulating hormone", "tsh"), "Thyroid Function", "0.35", "4.94", "", "", "", ""),
    ClinicalMarkerDef("free_t4", "Serum free T4", "pmol/L", listOf("Serum free T4", "serum free t4 level", "free t4 level", "free thyroxine", "free t4", "ft4"), "Thyroid Function", "9.0", "19.1", "", "", "", ""),
    ClinicalMarkerDef("prothrombin_time", "Prothrombin time", "sec", listOf("prothrombin time", "pt time", "pt"), "Clotting Screen", "9.7", "12.0", "", "", "", ""),
    ClinicalMarkerDef("inr", "International normalised ratio", "Ratio", listOf("international normalised ratio", "international normalized ratio", "inr"), "Clotting Screen", "0.8", "1.2", "", "", "", ""),
    ClinicalMarkerDef("aptt", "APTT", "sec", listOf("activated partial thromboplastin time", "aptt"), "Clotting Screen", "21.0", "29.0", "", "", "", ""),
    ClinicalMarkerDef("aptt_ratio", "APTT ratio", "Ratio", listOf("aptt ratio", "activated partial thromboplastin time ratio"), "Clotting Screen", "0.8", "1.2", "", "", "", ""),
    ClinicalMarkerDef("sodium", "Serum sodium", "mmol/L", listOf("serum sodium level", "serum sodium", "sodium"), "Renal Profile", "133", "146", "", "", "", ""),
    ClinicalMarkerDef("potassium", "Serum potassium", "mmol/L", listOf("serum potassium level", "serum potassium", "potassium"), "Renal Profile", "3.5", "5.3", "", "", "", ""),
    ClinicalMarkerDef("creatinine", "Serum creatinine", "umol/L", listOf("serum creatinine level", "serum creatinine", "creatinine"), "Renal Profile", "64", "104", "", "", "", ""),
    ClinicalMarkerDef("egfr", "eGFRcreat (CKD-EPI)/1.73 m²", "mL/min/1.73m2", listOf("eGFRcreat (CKD-EPI)/1.73 m²", "egfrcreat ckd-epi", "egfrcreat", "egfr ckd-epi", "estimated glomerular filtration rate", "egfr"), "Renal Profile", "90", "", "", "", "", ""),
    ClinicalMarkerDef("rheumatoid_factor", "Rheumatoid factor", "IU/mL", listOf("rheumatoid factor", "rf"), "Autoimmune", "", "20", "", "", "", ""),
    ClinicalMarkerDef("reticulocytes", "Reticulocyte count", "%", listOf("reticulocyte count", "reticulocytes", "retic count", "retics"), "Full Blood Count", "0.5", "2.0", "", "", "", ""),
    ClinicalMarkerDef("fibrinogen", "Fibrinogen", "g/L", listOf("fibrinogen", "fibrinogen level"), "Clotting Screen", "1.50", "4.50", "", "", "", ""),
    ClinicalMarkerDef("d_dimer", "D-dimer", "ng/mL", listOf("d-dimer", "d dimer", "d-dimer for dvt", "d-dimer for pe"), "Clotting Screen", "", "", "", "", "", ""),
    ClinicalMarkerDef("drvv_time", "DRVVT time", "sec", listOf("DRVVT time", "drvvt", "dilute russell viper venom time", "drvv time"), "Clotting Screen", "30", "50", "", "", "", ""),
    ClinicalMarkerDef("drvv_ratio", "DRVVT ratio", "Ratio", listOf("drvvt ratio", "drvv ratio"), "Clotting Screen", "0.8", "1.2", "", "", "", ""),
    ClinicalMarkerDef("protein_s_total", "Protein S total", "%", listOf("protein s total", "total protein s"), "Thrombophilia", "62", "156", "", "", "", ""),
    ClinicalMarkerDef("protein_s_free", "Protein S free", "%", listOf("protein s free", "free protein s"), "Thrombophilia", "", "", "72", "123", "55", "124"),
    ClinicalMarkerDef("protein_c", "Protein C activity", "%", listOf("protein c activity", "protein c"), "Thrombophilia", "70", "140", "", "", "", ""),
    ClinicalMarkerDef("antithrombin", "Antithrombin", "%", listOf("antithrombin", "antithrombin iii", "at iii"), "Thrombophilia", "83", "128", "", "", "", ""),
    ClinicalMarkerDef("factor_ii", "Factor II", "%", listOf("factor ii", "factor 2"), "Coagulation Factors", "50", "150", "", "", "", ""),
    ClinicalMarkerDef("factor_v", "Factor V", "%", listOf("factor v", "factor 5"), "Coagulation Factors", "50", "150", "", "", "", ""),
    ClinicalMarkerDef("factor_vii", "Factor VII", "%", listOf("factor vii", "factor 7"), "Coagulation Factors", "50", "129", "", "", "", ""),
    ClinicalMarkerDef("factor_viii", "Factor VIII", "%", listOf("factor viii", "factor 8"), "Coagulation Factors", "50", "150", "", "", "", ""),
    ClinicalMarkerDef("factor_ix", "Factor IX", "%", listOf("factor ix", "factor 9"), "Coagulation Factors", "65", "150", "", "", "", ""),
    ClinicalMarkerDef("factor_x", "Factor X", "%", listOf("factor x", "factor 10"), "Coagulation Factors", "50", "150", "", "", "", ""),
    ClinicalMarkerDef("factor_xi", "Factor XI", "%", listOf("factor xi", "factor 11"), "Coagulation Factors", "65", "150", "", "", "", ""),
    ClinicalMarkerDef("factor_xii", "Factor XII", "%", listOf("factor xii", "factor 12"), "Coagulation Factors", "50", "150", "", "", "", ""),
    ClinicalMarkerDef("factor_xiii", "Factor XIII", "IU/mL", listOf("factor xiii", "factor 13"), "Coagulation Factors", "0.7", "1.4", "", "", "", ""),
    ClinicalMarkerDef("vitamin_b12", "Vitamin B12", "ng/L", listOf("vitamin b12", "serum vitamin b12", "b12"), "Haematinics", "145", "914", "", "", "", ""),
    ClinicalMarkerDef("folate", "Serum folate", "ug/L", listOf("serum folate", "folate", "folic acid"), "Haematinics", "4.0", "", "", "", "", ""),
    ClinicalMarkerDef("plasma_viscosity", "Plasma viscosity", "mPa.s", listOf("plasma viscosity", "pv"), "Inflammation", "1.50", "1.72", "", "", "", ""),
    ClinicalMarkerDef("esr", "ESR", "mm/h", listOf("erythrocyte sedimentation rate", "esr"), "Inflammation", "", "", "", "", "", ""),
    ClinicalMarkerDef("hba2", "HbA2", "%", listOf("hba2", "haemoglobin a2", "hemoglobin a2"), "Haemoglobinopathy", "1.8", "3.5", "", "", "", ""),
    ClinicalMarkerDef("hbf", "HbF", "%", listOf("hbf", "foetal haemoglobin", "fetal hemoglobin", "haemoglobin f"), "Haemoglobinopathy", "0.0", "2.0", "", "", "", ""),
    ClinicalMarkerDef("urea", "Urea", "mmol/L", listOf("serum urea", "urea"), "Renal Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("chloride", "Chloride", "mmol/L", listOf("serum chloride", "chloride"), "Renal Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("bicarbonate", "Bicarbonate", "mmol/L", listOf("serum bicarbonate", "bicarbonate", "total co2"), "Renal Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("osmolality_serum", "Serum osmolality", "mOsm/kg", listOf("serum osmolality", "plasma osmolality"), "Renal Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("osmolality_urine", "Urine osmolality", "mOsm/kg", listOf("urine osmolality"), "Urine Chemistry", "", "", "", "", "", ""),
    ClinicalMarkerDef("urine_sodium", "Urine sodium", "mmol/L", listOf("urine sodium"), "Urine Chemistry", "", "", "", "", "", ""),
    ClinicalMarkerDef("acr", "Urine albumin:creatinine ratio", "mg/mmol", listOf("Urine albumin:creatinine ratio", "albumin creatinine ratio", "albumin:creatinine ratio", "urine acr", "acr"), "Urine Chemistry", "", "", "", "", "", ""),
    ClinicalMarkerDef("pcr", "Urine protein:creatinine ratio", "mg/mmol", listOf("Urine protein:creatinine ratio", "protein creatinine ratio", "protein:creatinine ratio", "urine pcr", "pcr"), "Urine Chemistry", "", "", "", "", "", ""),
    ClinicalMarkerDef("ggt", "GGT", "U/L", listOf("gamma glutamyl transferase", "gamma-gt", "gamma gt", "ggt"), "Liver Panel", "", "", "", "", "", ""),
    ClinicalMarkerDef("ldh", "LDH", "U/L", listOf("lactate dehydrogenase", "ldh"), "Liver Panel", "", "", "", "", "", ""),
    ClinicalMarkerDef("magnesium", "Magnesium", "mmol/L", listOf("serum magnesium", "magnesium"), "Bone & Minerals", "", "", "", "", "", ""),
    ClinicalMarkerDef("pth", "Parathyroid hormone", "pmol/L", listOf("parathyroid hormone", "intact pth", "pth"), "Bone & Minerals", "", "", "", "", "", ""),
    ClinicalMarkerDef("vitamin_d", "25-OH Vitamin D", "nmol/L", listOf("25-hydroxyvitamin d", "25 hydroxy vitamin d", "25-oh vitamin d", "vitamin d"), "Vitamins", "", "", "", "", "", ""),
    ClinicalMarkerDef("zinc", "Zinc", "umol/L", listOf("serum zinc", "plasma zinc", "zinc"), "Trace Elements", "", "", "", "", "", ""),
    ClinicalMarkerDef("selenium", "Selenium", "umol/L", listOf("serum selenium", "selenium"), "Trace Elements", "", "", "", "", "", ""),
    ClinicalMarkerDef("copper", "Copper", "umol/L", listOf("serum copper", "copper"), "Trace Elements", "", "", "", "", "", ""),
    ClinicalMarkerDef("caeruloplasmin", "Caeruloplasmin", "g/L", listOf("caeruloplasmin", "ceruloplasmin"), "Trace Elements", "", "", "", "", "", ""),
    ClinicalMarkerDef("cholesterol_total", "Total cholesterol", "mmol/L", listOf("total cholesterol", "serum cholesterol", "cholesterol"), "Lipid Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("hdl", "HDL cholesterol", "mmol/L", listOf("hdl cholesterol", "hdl-c", "hdl"), "Lipid Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("ldl", "LDL cholesterol", "mmol/L", listOf("ldl cholesterol", "ldl-c", "ldl"), "Lipid Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("non_hdl", "Non-HDL cholesterol", "mmol/L", listOf("non-hdl cholesterol", "non hdl cholesterol", "non-hdl"), "Lipid Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("triglycerides", "Triglycerides", "mmol/L", listOf("serum triglycerides", "triglycerides"), "Lipid Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("chol_hdl_ratio", "Total cholesterol:HDL ratio", "Ratio", listOf("Total cholesterol:HDL ratio", "cholesterol hdl ratio", "total cholesterol hdl ratio", "tc hdl ratio"), "Lipid Profile", "", "", "", "", "", ""),
    ClinicalMarkerDef("glucose", "Glucose", "mmol/L", listOf("serum glucose", "plasma glucose", "glucose"), "Diabetes & Metabolic", "", "", "", "", "", ""),
    ClinicalMarkerDef("fasting_glucose", "Fasting glucose", "mmol/L", listOf("fasting plasma glucose", "fasting glucose"), "Diabetes & Metabolic", "", "", "", "", "", ""),
    ClinicalMarkerDef("hba1c", "HbA1c", "mmol/mol", listOf("hba1c", "haemoglobin a1c", "hemoglobin a1c"), "Diabetes & Metabolic", "", "", "", "", "", ""),
    ClinicalMarkerDef("insulin", "Insulin", "mU/L", listOf("serum insulin", "fasting insulin", "insulin"), "Diabetes & Metabolic", "", "", "", "", "", ""),
    ClinicalMarkerDef("c_peptide", "C-peptide", "nmol/L", listOf("c-peptide", "c peptide"), "Diabetes & Metabolic", "", "", "", "", "", ""),
    ClinicalMarkerDef("lactate", "Lactate", "mmol/L", listOf("blood lactate", "plasma lactate", "lactate"), "Diabetes & Metabolic", "", "", "", "", "", ""),
    ClinicalMarkerDef("free_t3", "Serum free T3", "pmol/L", listOf("serum free t3", "free t3", "free triiodothyronine", "ft3"), "Thyroid Function", "", "", "", "", "", ""),
    ClinicalMarkerDef("tpo_ab", "Thyroid peroxidase antibodies", "kU/L", listOf("thyroid peroxidase antibodies", "tpo antibodies", "tpo ab", "anti-tpo"), "Thyroid Autoantibodies", "", "", "", "", "", ""),
    ClinicalMarkerDef("tg_ab", "Thyroglobulin antibodies", "kU/L", listOf("thyroglobulin antibodies", "tg antibodies", "tg ab"), "Thyroid Autoantibodies", "", "", "", "", "", ""),
    ClinicalMarkerDef("trab", "TSH receptor antibodies", "IU/L", listOf("tsh receptor antibodies", "trab"), "Thyroid Autoantibodies", "", "", "", "", "", ""),
    ClinicalMarkerDef("crp", "C-reactive protein", "mg/L", listOf("c-reactive protein", "crp"), "Inflammation", "", "", "", "", "", ""),
    ClinicalMarkerDef("anti_ccp", "Anti-CCP antibodies", "U/mL", listOf("Anti-CCP antibodies", "anti-ccp", "anti ccp", "cyclic citrullinated peptide antibodies", "ccp antibodies"), "Autoimmune", "", "", "", "", "", ""),
    ClinicalMarkerDef("ana", "ANA", "Titre", listOf("antinuclear antibody", "antinuclear antibodies", "ana"), "Autoimmune", "", "", "", "", "", ""),
    ClinicalMarkerDef("igg", "Immunoglobulin G", "g/L", listOf("immunoglobulin g", "igg"), "Immunology", "", "", "", "", "", ""),
    ClinicalMarkerDef("iga", "Immunoglobulin A", "g/L", listOf("immunoglobulin a", "iga"), "Immunology", "", "", "", "", "", ""),
    ClinicalMarkerDef("igm", "Immunoglobulin M", "g/L", listOf("immunoglobulin m", "igm"), "Immunology", "", "", "", "", "", ""),
    ClinicalMarkerDef("c3", "Complement C3", "g/L", listOf("complement c3", "c3 complement", "c3"), "Immunology", "", "", "", "", "", ""),
    ClinicalMarkerDef("c4", "Complement C4", "g/L", listOf("complement c4", "c4 complement", "c4"), "Immunology", "", "", "", "", "", ""),
    ClinicalMarkerDef("ttg_iga", "Tissue transglutaminase IgA", "U/mL", listOf("tissue transglutaminase iga", "ttg iga", "tTG-IgA"), "Coeliac Screen", "", "", "", "", "", ""),
    ClinicalMarkerDef("testosterone", "Testosterone", "nmol/L", listOf("serum testosterone", "total testosterone", "testosterone"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("shbg", "SHBG", "nmol/L", listOf("sex hormone binding globulin", "shbg"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("free_testosterone", "Free testosterone", "pmol/L", listOf("free testosterone", "calculated free testosterone"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("lh", "LH", "IU/L", listOf("luteinising hormone", "luteinizing hormone", "lh"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("fsh", "FSH", "IU/L", listOf("follicle stimulating hormone", "fsh"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("prolactin", "Prolactin", "mIU/L", listOf("serum prolactin", "prolactin"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("oestradiol", "Oestradiol", "pmol/L", listOf("oestradiol", "estradiol", "e2"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("progesterone", "Progesterone", "nmol/L", listOf("serum progesterone", "progesterone"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("cortisol", "Cortisol", "nmol/L", listOf("serum cortisol", "cortisol"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("acth", "ACTH", "ng/L", listOf("adrenocorticotropic hormone", "acth"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("dheas", "DHEAS", "umol/L", listOf("dheas", "dhea-s", "dehydroepiandrosterone sulfate"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("igf1", "IGF-1", "nmol/L", listOf("igf-1", "igf1", "insulin-like growth factor 1"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("growth_hormone", "Growth hormone", "ug/L", listOf("growth hormone", "gh"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("aldosterone", "Aldosterone", "pmol/L", listOf("aldosterone"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("renin", "Renin", "mU/L", listOf("plasma renin", "renin"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("amh", "AMH", "pmol/L", listOf("anti-mullerian hormone", "anti mullerian hormone", "amh"), "Hormones", "", "", "", "", "", ""),
    ClinicalMarkerDef("troponin_t", "Troponin T", "ng/L", listOf("troponin t", "high sensitivity troponin t", "hs troponin t", "hs-tnt"), "Cardiac", "", "", "", "", "", ""),
    ClinicalMarkerDef("troponin_i", "Troponin I", "ng/L", listOf("troponin i", "high sensitivity troponin i", "hs troponin i", "hs-tni"), "Cardiac", "", "", "", "", "", ""),
    ClinicalMarkerDef("nt_probnp", "NT-proBNP", "ng/L", listOf("nt-probnp", "nt probnp", "n-terminal pro bnp"), "Cardiac", "", "", "", "", "", ""),
    ClinicalMarkerDef("bnp", "BNP", "ng/L", listOf("b-type natriuretic peptide", "bnp"), "Cardiac", "", "", "", "", "", ""),
    ClinicalMarkerDef("ck", "Creatine kinase", "U/L", listOf("creatine kinase", "ck"), "Muscle & Cardiac", "", "", "", "", "", ""),
    ClinicalMarkerDef("ck_mb", "CK-MB", "ug/L", listOf("ck-mb", "ck mb"), "Cardiac", "", "", "", "", "", ""),
    ClinicalMarkerDef("amylase", "Amylase", "U/L", listOf("serum amylase", "amylase"), "Pancreas & GI", "", "", "", "", "", ""),
    ClinicalMarkerDef("lipase", "Lipase", "U/L", listOf("serum lipase", "lipase"), "Pancreas & GI", "", "", "", "", "", ""),
    ClinicalMarkerDef("faecal_calprotectin", "Faecal calprotectin", "ug/g", listOf("faecal calprotectin", "fecal calprotectin", "calprotectin"), "Pancreas & GI", "", "", "", "", "", ""),
    ClinicalMarkerDef("urate", "Urate", "umol/L", listOf("serum urate", "uric acid", "urate"), "Metabolic", "", "", "", "", "", ""),
    ClinicalMarkerDef("ammonia", "Ammonia", "umol/L", listOf("plasma ammonia", "ammonia"), "Metabolic", "", "", "", "", "", ""),
    ClinicalMarkerDef("haptoglobin", "Haptoglobin", "g/L", listOf("serum haptoglobin", "haptoglobin"), "Haemolysis", "", "", "", "", "", ""),
    ClinicalMarkerDef("free_kappa", "Free kappa light chains", "mg/L", listOf("free kappa light chains", "kappa free light chains"), "Protein Studies", "", "", "", "", "", ""),
    ClinicalMarkerDef("free_lambda", "Free lambda light chains", "mg/L", listOf("free lambda light chains", "lambda free light chains"), "Protein Studies", "", "", "", "", "", ""),
    ClinicalMarkerDef("kappa_lambda_ratio", "Kappa/lambda ratio", "Ratio", listOf("kappa lambda ratio", "kappa/lambda ratio"), "Protein Studies", "", "", "", "", "", ""),
    ClinicalMarkerDef("urine_protein", "Urine protein", "mg/L", listOf("urine protein", "protein urine"), "Urine Chemistry", "", "", "", "", "", ""),
    ClinicalMarkerDef("urine_albumin", "Urine albumin", "mg/L", listOf("urine albumin", "microalbumin"), "Urine Chemistry", "", "", "", "", "", ""),
    ClinicalMarkerDef("urine_creatinine", "Urine creatinine", "mmol/L", listOf("urine creatinine"), "Urine Chemistry", "", "", "", "", "", ""),
    ClinicalMarkerDef("systolic", "Systolic blood pressure", "mmHg", listOf("systolic blood pressure", "systolic", "sys"), "Vitals", "", "", "", "", "", ""),
    ClinicalMarkerDef("diastolic", "Diastolic blood pressure", "mmHg", listOf("diastolic blood pressure", "diastolic", "dia"), "Vitals", "", "", "", "", "", ""),
    ClinicalMarkerDef("pulse", "Pulse", "bpm", listOf("pulse rate", "heart rate", "pulse", "pul"), "Vitals", "", "", "", "", "", ""),
)

internal val CLINICAL_MARKER_BY_ID: Map<String, ClinicalMarkerDef> = CLINICAL_MARKER_REGISTRY.associateBy { it.id }
